@startuml
skinparam monochrome true
hide empty members
hide circle

Eve_1 .right. Adam_1
Adam_1 --> Cain_1
Eve_1 --> Cain_1
Adam_1 --> Abel_1
Eve_1 --> Abel_1
Cain_1 --> Enoch_1
Enoch_1 --> Irad_1
Irad_1 --> Mehujael_1
Mehujael_1 --> Methushael_1
Methushael_1 --> Lamech_1
Adah_1 .right. Lamech_1
Zillah_1 .right. Lamech_1
Lamech_1 --> Jabal_1
Adah_1 --> Jabal_1
Lamech_1 --> Jubal_1
Adah_1 --> Jubal_1
@enduml
